    namespace Systematycznosc.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddedGoalTillH : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Goals", "CGoalName", c => c.String());
            AddColumn("dbo.Goals", "DGoalName", c => c.String());
            AddColumn("dbo.Goals", "EGoalName", c => c.String());
            AddColumn("dbo.Goals", "FGoalName", c => c.String());
            AddColumn("dbo.Goals", "GGoalName", c => c.String());
            AddColumn("dbo.Goals", "HGoalName", c => c.String());
            AddColumn("dbo.Goals", "CGoalQuestion", c => c.String());
            AddColumn("dbo.Goals", "DGoalQuestion", c => c.String());
            AddColumn("dbo.Goals", "EGoalQuestion", c => c.String());
            AddColumn("dbo.Goals", "FGoalQuestion", c => c.String());
            AddColumn("dbo.Goals", "GGoalQuestion", c => c.String());
            AddColumn("dbo.Goals", "HGoalQuestion", c => c.String());
            AddColumn("dbo.Goals", "CGoalDays", c => c.String());
            AddColumn("dbo.Goals", "DGoalDays", c => c.String());
            AddColumn("dbo.Goals", "EGoalDays", c => c.String());
            AddColumn("dbo.Goals", "FGoalDays", c => c.String());
            AddColumn("dbo.Goals", "GGoalDays", c => c.String());
            AddColumn("dbo.Goals", "HGoalDays", c => c.String());
            AddColumn("dbo.Goals", "CGoal1", c => c.String());
            AddColumn("dbo.Goals", "CGoal2", c => c.String());
            AddColumn("dbo.Goals", "CGoal3", c => c.String());
            AddColumn("dbo.Goals", "CGoal4", c => c.String());
            AddColumn("dbo.Goals", "CGoal5", c => c.String());
            AddColumn("dbo.Goals", "CGoal6", c => c.String());
            AddColumn("dbo.Goals", "CGoal7", c => c.String());
            AddColumn("dbo.Goals", "DGoal1", c => c.String());
            AddColumn("dbo.Goals", "DGoal2", c => c.String());
            AddColumn("dbo.Goals", "DGoal3", c => c.String());
            AddColumn("dbo.Goals", "DGoal4", c => c.String());
            AddColumn("dbo.Goals", "DGoal5", c => c.String());
            AddColumn("dbo.Goals", "DGoal6", c => c.String());
            AddColumn("dbo.Goals", "DGoal7", c => c.String());
            AddColumn("dbo.Goals", "EGoal1", c => c.String());
            AddColumn("dbo.Goals", "EGoal2", c => c.String());
            AddColumn("dbo.Goals", "EGoal3", c => c.String());
            AddColumn("dbo.Goals", "EGoal4", c => c.String());
            AddColumn("dbo.Goals", "EGoal5", c => c.String());
            AddColumn("dbo.Goals", "EGoal6", c => c.String());
            AddColumn("dbo.Goals", "EGoal7", c => c.String());
            AddColumn("dbo.Goals", "FGoal1", c => c.String());
            AddColumn("dbo.Goals", "FGoal2", c => c.String());
            AddColumn("dbo.Goals", "FGoal3", c => c.String());
            AddColumn("dbo.Goals", "FGoal4", c => c.String());
            AddColumn("dbo.Goals", "FGoal5", c => c.String());
            AddColumn("dbo.Goals", "FGoal6", c => c.String());
            AddColumn("dbo.Goals", "FGoal7", c => c.String());
            AddColumn("dbo.Goals", "GGoal1", c => c.String());
            AddColumn("dbo.Goals", "GGoal2", c => c.String());
            AddColumn("dbo.Goals", "GGoal3", c => c.String());
            AddColumn("dbo.Goals", "GGoal4", c => c.String());
            AddColumn("dbo.Goals", "GGoal5", c => c.String());
            AddColumn("dbo.Goals", "GGoal6", c => c.String());
            AddColumn("dbo.Goals", "GGoal7", c => c.String());
            AddColumn("dbo.Goals", "HGoal1", c => c.String());
            AddColumn("dbo.Goals", "HGoal2", c => c.String());
            AddColumn("dbo.Goals", "HGoal3", c => c.String());
            AddColumn("dbo.Goals", "HGoal4", c => c.String());
            AddColumn("dbo.Goals", "HGoal5", c => c.String());
            AddColumn("dbo.Goals", "HGoal6", c => c.String());
            AddColumn("dbo.Goals", "HGoal7", c => c.String());
            AddColumn("dbo.Goals", "CGoalDate1", c => c.DateTime());
            AddColumn("dbo.Goals", "CGoalDate2", c => c.DateTime());
            AddColumn("dbo.Goals", "CGoalDate3", c => c.DateTime());
            AddColumn("dbo.Goals", "CGoalDate4", c => c.DateTime());
            AddColumn("dbo.Goals", "CGoalDate5", c => c.DateTime());
            AddColumn("dbo.Goals", "CGoalDate6", c => c.DateTime());
            AddColumn("dbo.Goals", "CGoalDate7", c => c.DateTime());
            AddColumn("dbo.Goals", "DGoalDate1", c => c.DateTime());
            AddColumn("dbo.Goals", "DGoalDate2", c => c.DateTime());
            AddColumn("dbo.Goals", "DGoalDate3", c => c.DateTime());
            AddColumn("dbo.Goals", "DGoalDate4", c => c.DateTime());
            AddColumn("dbo.Goals", "DGoalDate5", c => c.DateTime());
            AddColumn("dbo.Goals", "DGoalDate6", c => c.DateTime());
            AddColumn("dbo.Goals", "DGoalDate7", c => c.DateTime());
            AddColumn("dbo.Goals", "EGoalDate1", c => c.DateTime());
            AddColumn("dbo.Goals", "EGoalDate2", c => c.DateTime());
            AddColumn("dbo.Goals", "EGoalDate3", c => c.DateTime());
            AddColumn("dbo.Goals", "EGoalDate4", c => c.DateTime());
            AddColumn("dbo.Goals", "EGoalDate5", c => c.DateTime());
            AddColumn("dbo.Goals", "EGoalDate6", c => c.DateTime());
            AddColumn("dbo.Goals", "EGoalDate7", c => c.DateTime());
            AddColumn("dbo.Goals", "FGoalDate1", c => c.DateTime());
            AddColumn("dbo.Goals", "FGoalDate2", c => c.DateTime());
            AddColumn("dbo.Goals", "FGoalDate3", c => c.DateTime());
            AddColumn("dbo.Goals", "FGoalDate4", c => c.DateTime());
            AddColumn("dbo.Goals", "FGoalDate5", c => c.DateTime());
            AddColumn("dbo.Goals", "FGoalDate6", c => c.DateTime());
            AddColumn("dbo.Goals", "FGoalDate7", c => c.DateTime());
            AddColumn("dbo.Goals", "GGoalDate1", c => c.DateTime());
            AddColumn("dbo.Goals", "GGoalDate2", c => c.DateTime());
            AddColumn("dbo.Goals", "GGoalDate3", c => c.DateTime());
            AddColumn("dbo.Goals", "GGoalDate4", c => c.DateTime());
            AddColumn("dbo.Goals", "GGoalDate5", c => c.DateTime());
            AddColumn("dbo.Goals", "GGoalDate6", c => c.DateTime());
            AddColumn("dbo.Goals", "GGoalDate7", c => c.DateTime());
            AddColumn("dbo.Goals", "HGoalDate1", c => c.DateTime());
            AddColumn("dbo.Goals", "HGoalDate2", c => c.DateTime());
            AddColumn("dbo.Goals", "HGoalDate3", c => c.DateTime());
            AddColumn("dbo.Goals", "HGoalDate4", c => c.DateTime());
            AddColumn("dbo.Goals", "HGoalDate5", c => c.DateTime());
            AddColumn("dbo.Goals", "HGoalDate6", c => c.DateTime());
            AddColumn("dbo.Goals", "HGoalDate7", c => c.DateTime());
        }
        
        public override void Down()
        {
            DropColumn("dbo.Goals", "HGoalDate7");
            DropColumn("dbo.Goals", "HGoalDate6");
            DropColumn("dbo.Goals", "HGoalDate5");
            DropColumn("dbo.Goals", "HGoalDate4");
            DropColumn("dbo.Goals", "HGoalDate3");
            DropColumn("dbo.Goals", "HGoalDate2");
            DropColumn("dbo.Goals", "HGoalDate1");
            DropColumn("dbo.Goals", "GGoalDate7");
            DropColumn("dbo.Goals", "GGoalDate6");
            DropColumn("dbo.Goals", "GGoalDate5");
            DropColumn("dbo.Goals", "GGoalDate4");
            DropColumn("dbo.Goals", "GGoalDate3");
            DropColumn("dbo.Goals", "GGoalDate2");
            DropColumn("dbo.Goals", "GGoalDate1");
            DropColumn("dbo.Goals", "FGoalDate7");
            DropColumn("dbo.Goals", "FGoalDate6");
            DropColumn("dbo.Goals", "FGoalDate5");
            DropColumn("dbo.Goals", "FGoalDate4");
            DropColumn("dbo.Goals", "FGoalDate3");
            DropColumn("dbo.Goals", "FGoalDate2");
            DropColumn("dbo.Goals", "FGoalDate1");
            DropColumn("dbo.Goals", "EGoalDate7");
            DropColumn("dbo.Goals", "EGoalDate6");
            DropColumn("dbo.Goals", "EGoalDate5");
            DropColumn("dbo.Goals", "EGoalDate4");
            DropColumn("dbo.Goals", "EGoalDate3");
            DropColumn("dbo.Goals", "EGoalDate2");
            DropColumn("dbo.Goals", "EGoalDate1");
            DropColumn("dbo.Goals", "DGoalDate7");
            DropColumn("dbo.Goals", "DGoalDate6");
            DropColumn("dbo.Goals", "DGoalDate5");
            DropColumn("dbo.Goals", "DGoalDate4");
            DropColumn("dbo.Goals", "DGoalDate3");
            DropColumn("dbo.Goals", "DGoalDate2");
            DropColumn("dbo.Goals", "DGoalDate1");
            DropColumn("dbo.Goals", "CGoalDate7");
            DropColumn("dbo.Goals", "CGoalDate6");
            DropColumn("dbo.Goals", "CGoalDate5");
            DropColumn("dbo.Goals", "CGoalDate4");
            DropColumn("dbo.Goals", "CGoalDate3");
            DropColumn("dbo.Goals", "CGoalDate2");
            DropColumn("dbo.Goals", "CGoalDate1");
            DropColumn("dbo.Goals", "HGoal7");
            DropColumn("dbo.Goals", "HGoal6");
            DropColumn("dbo.Goals", "HGoal5");
            DropColumn("dbo.Goals", "HGoal4");
            DropColumn("dbo.Goals", "HGoal3");
            DropColumn("dbo.Goals", "HGoal2");
            DropColumn("dbo.Goals", "HGoal1");
            DropColumn("dbo.Goals", "GGoal7");
            DropColumn("dbo.Goals", "GGoal6");
            DropColumn("dbo.Goals", "GGoal5");
            DropColumn("dbo.Goals", "GGoal4");
            DropColumn("dbo.Goals", "GGoal3");
            DropColumn("dbo.Goals", "GGoal2");
            DropColumn("dbo.Goals", "GGoal1");
            DropColumn("dbo.Goals", "FGoal7");
            DropColumn("dbo.Goals", "FGoal6");
            DropColumn("dbo.Goals", "FGoal5");
            DropColumn("dbo.Goals", "FGoal4");
            DropColumn("dbo.Goals", "FGoal3");
            DropColumn("dbo.Goals", "FGoal2");
            DropColumn("dbo.Goals", "FGoal1");
            DropColumn("dbo.Goals", "EGoal7");
            DropColumn("dbo.Goals", "EGoal6");
            DropColumn("dbo.Goals", "EGoal5");
            DropColumn("dbo.Goals", "EGoal4");
            DropColumn("dbo.Goals", "EGoal3");
            DropColumn("dbo.Goals", "EGoal2");
            DropColumn("dbo.Goals", "EGoal1");
            DropColumn("dbo.Goals", "DGoal7");
            DropColumn("dbo.Goals", "DGoal6");
            DropColumn("dbo.Goals", "DGoal5");
            DropColumn("dbo.Goals", "DGoal4");
            DropColumn("dbo.Goals", "DGoal3");
            DropColumn("dbo.Goals", "DGoal2");
            DropColumn("dbo.Goals", "DGoal1");
            DropColumn("dbo.Goals", "CGoal7");
            DropColumn("dbo.Goals", "CGoal6");
            DropColumn("dbo.Goals", "CGoal5");
            DropColumn("dbo.Goals", "CGoal4");
            DropColumn("dbo.Goals", "CGoal3");
            DropColumn("dbo.Goals", "CGoal2");
            DropColumn("dbo.Goals", "CGoal1");
            DropColumn("dbo.Goals", "HGoalDays");
            DropColumn("dbo.Goals", "GGoalDays");
            DropColumn("dbo.Goals", "FGoalDays");
            DropColumn("dbo.Goals", "EGoalDays");
            DropColumn("dbo.Goals", "DGoalDays");
            DropColumn("dbo.Goals", "CGoalDays");
            DropColumn("dbo.Goals", "HGoalQuestion");
            DropColumn("dbo.Goals", "GGoalQuestion");
            DropColumn("dbo.Goals", "FGoalQuestion");
            DropColumn("dbo.Goals", "EGoalQuestion");
            DropColumn("dbo.Goals", "DGoalQuestion");
            DropColumn("dbo.Goals", "CGoalQuestion");
            DropColumn("dbo.Goals", "HGoalName");
            DropColumn("dbo.Goals", "GGoalName");
            DropColumn("dbo.Goals", "FGoalName");
            DropColumn("dbo.Goals", "EGoalName");
            DropColumn("dbo.Goals", "DGoalName");
            DropColumn("dbo.Goals", "CGoalName");
        }
    }
}
